### ISSUE TITLE
error after trying to use the compiled version

### ISSUE THREAD

**Issue by M4K14** [m-o-s-t-a-f-a/dana#3]
The procedure entry point _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE could not be located in the dynamic link library libstdc  -6.dll.

**Comment by b00f** [comment]
Unfortunately I don't have windows. I try to fix it soon. Sorry for inconvenience.

**Comment by b00f** [comment]
Hi. Thanks for using Dana. I have published new installer for windows. It's automatically built. Please check the release page for downloading it. Let me know if you don't have any problem using it, then I can close this issue.
https://github.com/b00f/dana/releases/tag/v1.3
