### ISSUE TITLE
error on windows compiled version

### ISSUE THREAD

**Issue by mostafasedaghat** [m-o-s-t-a-f-a/dana#4]
![sketch](https://user-images.githubusercontent.com/549274/36382431-1becf2ee-159e-11e8-8140-4bddde91fcf3.png)
when i try to open dana on windows 10 64 bit

**Comment by b00f** [comment]
Unfortunately I don't have windows. I try to fix it soon. Sorry for inconvenience.

**Comment by b00f** [comment]
Hi. Thanks for using Dana. I have published new installer for windows. It's automatically built. Please check the release page for downloading it. Let me know if you don't have any problem using it, then I can close this issue.
https://github.com/b00f/dana/releases/tag/v1.3
